[versions]
kotlin = "2.0.0"
shadow = "8.3.3"
simpleCloudController = "0.0.30-dev.e3e27fc"
paper = "1.20.6-R0.1-SNAPSHOT"
cloudCommands = "2.0.0-beta.10"
cloudAnnotationCommands = "2.0.0"
interfaces = "1.2.0"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cloudMinecraftExtras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloudCommands" }
cloudPaper = { module = "org.incendo:cloud-paper", version.ref = "cloudCommands" }
cloudAnnotation = { module = "org.incendo:cloud-annotations", version.ref = "cloudAnnotationCommands" }

simpleCloudControllerApi = { module = "app.simplecloud.controller:controller-api", version.ref = "simpleCloudController" }
simpleCloudControllerShared = { module = "app.simplecloud.controller:controller-shared", version.ref = "simpleCloudController" }

interfacesApi = { module = "com.noxcrew.interfaces:interfaces", version.ref = "interfaces" }

[bundles]
simpleCloudController = ["simpleCloudControllerApi", "simpleCloudControllerShared"]
cloudPaper = ["cloudPaper", "cloudMinecraftExtras", "cloudAnnotation"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }